package ticketing.system;

import java.awt.Dimension;
import java.awt.Toolkit;

public class main_menu extends javax.swing.JFrame {

    /**
     * Creates new form main_menu
     */
    public main_menu() {
        int lebar = this.getWidth()/2;
        int tinggi = this.getHeight()/2;
        int x = (Toolkit.getDefaultToolkit().getScreenSize().width/3)-lebar;
        int y = (Toolkit.getDefaultToolkit().getScreenSize().height/4)-tinggi;
        this.setLocation(x , y);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttons = new javax.swing.JPanel();
        book_flight_button = new javax.swing.JButton();
        exit_system = new javax.swing.JButton();
        manage_flight_button = new javax.swing.JButton();
        stats = new javax.swing.JPanel();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticketing System: Main Menu");
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Aller Display", 0, 14)); // NOI18N
        setResizable(false);

        buttons.setBackground(new java.awt.Color(75, 75, 75));

        book_flight_button.setBackground(new java.awt.Color(74, 144, 226));
        book_flight_button.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        book_flight_button.setText("Book a Flight");
        book_flight_button.setBorder(null);
        book_flight_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        book_flight_button.setFocusPainted(false);
        book_flight_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_flight_buttonActionPerformed(evt);
            }
        });

        exit_system.setBackground(new java.awt.Color(74, 144, 226));
        exit_system.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        exit_system.setText("Exit");
        exit_system.setBorder(null);
        exit_system.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_system.setFocusPainted(false);
        exit_system.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_systemActionPerformed(evt);
            }
        });

        manage_flight_button.setBackground(new java.awt.Color(74, 144, 226));
        manage_flight_button.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        manage_flight_button.setText("Manage Flight");
        manage_flight_button.setBorder(null);
        manage_flight_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manage_flight_button.setFocusPainted(false);
        manage_flight_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_flight_buttonActionPerformed(evt);
            }
        });

        stats.setBackground(new java.awt.Color(74, 144, 226));
        stats.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Ticketing System : Group 6");

        javax.swing.GroupLayout statsLayout = new javax.swing.GroupLayout(stats);
        stats.setLayout(statsLayout);
        statsLayout.setHorizontalGroup(
            statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        statsLayout.setVerticalGroup(
            statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout buttonsLayout = new javax.swing.GroupLayout(buttons);
        buttons.setLayout(buttonsLayout);
        buttonsLayout.setHorizontalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(book_flight_button, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(exit_system, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manage_flight_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonsLayout.setVerticalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsLayout.createSequentialGroup()
                .addComponent(stats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(book_flight_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manage_flight_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit_system, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        getContentPane().add(buttons, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_systemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_systemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_systemActionPerformed

    private void book_flight_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_flight_buttonActionPerformed
        this.setVisible(false);
        book_flight menu = new book_flight();
        menu.setBounds(this.getX(), this.getY(), 570 , 450);
        menu.setVisible(true);
    }//GEN-LAST:event_book_flight_buttonActionPerformed

    private void manage_flight_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_flight_buttonActionPerformed
        this.setVisible(false);
        flight_mod menu = new flight_mod();
        menu.setBounds(this.getX(), this.getY(), 600 , 470);
        menu.setVisible(true);
    }//GEN-LAST:event_manage_flight_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book_flight_button;
    private javax.swing.JPanel buttons;
    private javax.swing.JButton exit_system;
    private javax.swing.JButton manage_flight_button;
    private javax.swing.JPanel stats;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
