/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiable.airlines;

/**
 *
 * @author admin
 */
public class AmiableAirlinesMM extends javax.swing.JFrame {

    /**
     * Creates new form AmiableAirlines2
     */
    public AmiableAirlinesMM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Book_button = new javax.swing.JButton();
        Check_Flight_button = new javax.swing.JButton();
        Exit_Conf_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(91, 202, 226));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("AMIABLE AIRLINES");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 360, 61));

        Book_button.setText("BOOK A FLIGHT");
        Book_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Book_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 167, 47));

        Check_Flight_button.setText("CHECK AVAILABLE FLIGHTS");
        Check_Flight_button.setMargin(new java.awt.Insets(2, -14, 2, -14));
        jPanel1.add(Check_Flight_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 167, 55));

        Exit_Conf_button.setText("EXIT");
        Exit_Conf_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_Conf_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Exit_Conf_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 713, 147, 47));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Downloads\\output-onlinepngtools (1).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jButton1.setText("Exit");
        jButton1.setMaximumSize(new java.awt.Dimension(109, 23));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 170, 60));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("\"The Sky is not the limit for us\"");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_Conf_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_Conf_buttonActionPerformed
    ExitConfirmationPanel Exit = new ExitConfirmationPanel();
    Exit.setBounds(this.getX(), this.getY(), Exit.getWidth(), Exit.getHeight());
    Exit.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Exit_Conf_buttonActionPerformed

    private void Book_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_buttonActionPerformed
    this.setVisible(false);
    Book_A_Flight booking = new Book_A_Flight();
    booking.setBounds(this.getX(), this.getY(), booking.getWidth(), booking.getHeight());
    booking.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Book_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AmiableAirlinesMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AmiableAirlinesMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AmiableAirlinesMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AmiableAirlinesMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AmiableAirlinesMM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Book_button;
    private javax.swing.JButton Check_Flight_button;
    private javax.swing.JButton Exit_Conf_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
