/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiable.airlines;

/**
 *
 * @author admin
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
 
    public NewJFrame() {
        initComponents();
        ExitConfirmationPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANELS = new javax.swing.JTabbedPane();
        MainMenu = new javax.swing.JPanel();
        ExitConfirmationPanel = new javax.swing.JPanel();
        Close = new javax.swing.JButton();
        CancelConf = new javax.swing.JButton();
        ConfirmLabel = new javax.swing.JLabel();
        ExitConB = new javax.swing.JButton();
        EnterbookingPanelB = new javax.swing.JButton();
        CheckAvailB = new javax.swing.JButton();
        CheckAvailFlights = new javax.swing.JPanel();
        BookingBackMM2 = new javax.swing.JButton();
        Booking = new javax.swing.JPanel();
        BookingBackMM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitConfirmationPanel.setBackground(new java.awt.Color(204, 204, 204));
        ExitConfirmationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));

        Close.setText("EXIT");
        Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        CancelConf.setText("CANCEL");
        CancelConf.setInheritsPopupMenu(true);
        CancelConf.setMargin(new java.awt.Insets(0, -3, 0, -5));
        CancelConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelConfActionPerformed(evt);
            }
        });

        ConfirmLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ConfirmLabel.setText("ARE YOU SURE?");

        javax.swing.GroupLayout ExitConfirmationPanelLayout = new javax.swing.GroupLayout(ExitConfirmationPanel);
        ExitConfirmationPanel.setLayout(ExitConfirmationPanelLayout);
        ExitConfirmationPanelLayout.setHorizontalGroup(
            ExitConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitConfirmationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExitConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExitConfirmationPanelLayout.createSequentialGroup()
                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(CancelConf, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitConfirmationPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ConfirmLabel)
                        .addGap(26, 26, 26))))
        );
        ExitConfirmationPanelLayout.setVerticalGroup(
            ExitConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitConfirmationPanelLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(ConfirmLabel)
                .addGap(52, 52, 52)
                .addGroup(ExitConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelConf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        MainMenu.add(ExitConfirmationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 180, 170));

        ExitConB.setText("EXIT");
        ExitConB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitConBActionPerformed(evt);
            }
        });
        MainMenu.add(ExitConB, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 348, -1, -1));

        EnterbookingPanelB.setText("BOOK A FLIGHT");
        EnterbookingPanelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterbookingPanelBActionPerformed(evt);
            }
        });
        MainMenu.add(EnterbookingPanelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 235, 178, -1));

        CheckAvailB.setText("CHECK AVAILABLE FLIGHTS");
        CheckAvailB.setMargin(new java.awt.Insets(0, -10, 0, -10));
        CheckAvailB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAvailBActionPerformed(evt);
            }
        });
        MainMenu.add(CheckAvailB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 269, 178, -1));

        PANELS.addTab("tab1", MainMenu);

        BookingBackMM2.setText("BACK");
        BookingBackMM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingBackMM2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CheckAvailFlightsLayout = new javax.swing.GroupLayout(CheckAvailFlights);
        CheckAvailFlights.setLayout(CheckAvailFlightsLayout);
        CheckAvailFlightsLayout.setHorizontalGroup(
            CheckAvailFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckAvailFlightsLayout.createSequentialGroup()
                .addContainerGap(506, Short.MAX_VALUE)
                .addComponent(BookingBackMM2)
                .addContainerGap())
        );
        CheckAvailFlightsLayout.setVerticalGroup(
            CheckAvailFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckAvailFlightsLayout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(BookingBackMM2)
                .addContainerGap())
        );

        PANELS.addTab("tab3", CheckAvailFlights);

        BookingBackMM.setText("BACK");
        BookingBackMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingBackMMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookingLayout = new javax.swing.GroupLayout(Booking);
        Booking.setLayout(BookingLayout);
        BookingLayout.setHorizontalGroup(
            BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingLayout.createSequentialGroup()
                .addContainerGap(506, Short.MAX_VALUE)
                .addComponent(BookingBackMM)
                .addContainerGap())
        );
        BookingLayout.setVerticalGroup(
            BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingLayout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(BookingBackMM)
                .addContainerGap())
        );

        PANELS.addTab("tab2", Booking);

        getContentPane().add(PANELS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitConBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitConBActionPerformed
    ExitConfirmationPanel.setVisible(true);
    }//GEN-LAST:event_ExitConBActionPerformed

    private void EnterbookingPanelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterbookingPanelBActionPerformed
    PANELS.setSelectedIndex(1);
    }//GEN-LAST:event_EnterbookingPanelBActionPerformed

    private void BookingBackMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingBackMMActionPerformed
    PANELS.setSelectedIndex(0);
    }//GEN-LAST:event_BookingBackMMActionPerformed

    private void CheckAvailBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAvailBActionPerformed
    PANELS.setSelectedIndex(2);        // TODO add your handling code here:
    }//GEN-LAST:event_CheckAvailBActionPerformed

    private void BookingBackMM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingBackMM2ActionPerformed
    PANELS.setSelectedIndex(0);
    }//GEN-LAST:event_BookingBackMM2ActionPerformed

    private void CancelConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelConfActionPerformed
        // TODO add your handling code here:
        ExitConfirmationPanel.setVisible(false);
    }//GEN-LAST:event_CancelConfActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
    System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Booking;
    private javax.swing.JButton BookingBackMM;
    private javax.swing.JButton BookingBackMM2;
    private javax.swing.JButton CancelConf;
    private javax.swing.JButton CheckAvailB;
    private javax.swing.JPanel CheckAvailFlights;
    private javax.swing.JButton Close;
    private javax.swing.JLabel ConfirmLabel;
    private javax.swing.JButton EnterbookingPanelB;
    private javax.swing.JButton ExitConB;
    private javax.swing.JPanel ExitConfirmationPanel;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JTabbedPane PANELS;
    // End of variables declaration//GEN-END:variables
}
